## taxize use case No. 2 - Make a phylogeny from species names alone

There is only functionality for plants right now in taxize. We hope to add more taxan groups soon.

```{r defaults, eval=TRUE, echo=FALSE, cache=TRUE}
opts_chunk$set(comment=NA, warning=FALSE, message=FALSE, fig.width=7, fig.height=6)
```

### Load libraries

```{r load}
library(taxize)
```

```{r thespecieslist, cache=TRUE}
splist <- c("Helianthus annuus", "Pinus contorta", "Collomia grandiflora", "Abies magnifica", "Rosa californica", "Datura wrightii", "Mimulus bicolor", "Nicotiana glauca", "Madia sativa", "Bartlettia scaposa")
```

### Phylomatic is a web service with an API that we can use to get a phylogeny. Fetch phylogeny from phylomatic 

```{r phylogeny, cache=TRUE, message=FALSE, warning=FALSE}
phylogeny <- phylomatic_tree(taxa=splist, taxnames=TRUE, get = 'POST', informat='newick', method = "phylomatic", storedtree = "R20120829", taxaformat = "slashpath", outformat = "newick", clean = "true", parallel=TRUE)
```

### Format tip-labels 

```{r, cache=TRUE}
phylogeny$tip.label <- capwords(phylogeny$tip.label, onlyfirst=TRUE)
```

### Plot phylogeny 

```{r, cache=TRUE}
plot(phylogeny)
```